sudo: required

language: generic

services:
  - docker

script:
  - docker-compose build app
  - docker-compose run --rm flake8
  - docker-compose run --rm test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bamx/flask-seed;
    fi

branches:
  only:
    - master
